version: "3"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-ctn
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lms
      RABBITMQ_DEFAULT_PASS: lms2004
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: h_learning_core
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
